const diseasesBySpecialty = {

 InternalMedicine: [
    { name: "Hypertension", severity: "chronic" },
    { name: "Diabetes Mellitus", severity: "chronic" },
    { name: "Anemia", severity: "moderate" },
    { name: "Asthma", severity: "chronic" },
    { name: "Chronic Kidney Disease", severity: "severe" },
    { name: "Acute Kidney Injury", severity: "acute" },
    { name: "Liver Cirrhosis", severity: "severe" },
    { name: "Hepatitis B", severity: "chronic" },
    { name: "Hepatitis C", severity: "chronic" },
    { name: "Gastritis", severity: "mild" },
    { name: "Peptic Ulcer", severity: "moderate" },
    { name: "GERD", severity: "chronic" },
    { name: "Irritable Bowel Syndrome", severity: "chronic" },
    { name: "Crohn’s Disease", severity: "chronic" },
    { name: "Ulcerative Colitis", severity: "chronic" },
    { name: "Hyperthyroidism", severity: "chronic" },
    { name: "Hypothyroidism", severity: "chronic" },
    { name: "Obesity", severity: "chronic" },
    { name: "Metabolic Syndrome", severity: "chronic" },
    { name: "Hyperlipidemia", severity: "chronic" },
    { name: "Gout", severity: "chronic" },
    { name: "Sepsis", severity: "severe" },
    { name: "Tuberculosis", severity: "chronic" },
    { name: "Pneumonia", severity: "acute" },
    { name: "COPD", severity: "chronic" },
    { name: "Pulmonary Embolism", severity: "severe" },
    { name: "Deep Vein Thrombosis", severity: "moderate" },
    { name: "Heart Failure", severity: "severe" },
    { name: "Arrhythmia", severity: "moderate" },
    { name: "Stroke", severity: "severe" },
    { name: "Syncope", severity: "mild" },
    { name: "Migraine", severity: "moderate" },
    { name: "Chronic Fatigue Syndrome", severity: "chronic" },
    { name: "Fibromyalgia", severity: "chronic" },
    { name: "Vitamin D Deficiency", severity: "mild" },
    { name: "Iron Deficiency", severity: "moderate" },
    { name: "Electrolyte Imbalance", severity: "moderate" },
    { name: "Dehydration", severity: "acute" },
    { name: "Acidosis", severity: "severe" },
    { name: "Alkalosis", severity: "moderate" },
    { name: "Pancreatitis", severity: "acute" },
    { name: "Gallstones", severity: "moderate" },
    { name: "Cholecystitis", severity: "acute" },
    { name: "Appendicitis", severity: "acute" },
    { name: "Diverticulitis", severity: "moderate" },
    { name: "Celiac Disease", severity: "chronic" },
    { name: "Food Poisoning", severity: "acute" },
    { name: "Lyme Disease", severity: "chronic" },
    { name: "HIV/AIDS", severity: "severe" },
    { name: "Malaria", severity: "acute" }
  ],

  Pediatrics: [
    { name: "Bronchiolitis", severity: "acute" },
    { name: "Childhood Asthma", severity: "chronic" },
    { name: "Diarrhea", severity: "acute" },
    { name: "Dehydration", severity: "acute" },
    { name: "Malnutrition", severity: "moderate" },
    { name: "Chickenpox", severity: "acute" },
    { name: "Measles", severity: "acute" },
    { name: "Mumps", severity: "acute" },
    { name: "Rubella", severity: "acute" },
    { name: "Whooping Cough", severity: "acute" },
    { name: "Croup", severity: "acute" },
    { name: "Tonsillitis", severity: "acute" },
    { name: "Ear Infection", severity: "acute" },
    { name: "Sinusitis", severity: "acute" },
    { name: "Pneumonia", severity: "acute" },
    { name: "Tuberculosis", severity: "chronic" },
    { name: "Rickets", severity: "chronic" },
    { name: "Congenital Heart Disease", severity: "severe" },
    { name: "Neonatal Jaundice", severity: "moderate" },
    { name: "Sepsis", severity: "severe" },
    { name: "ADHD", severity: "chronic" },
    { name: "Autism Spectrum Disorder", severity: "chronic" },
    { name: "Epilepsy", severity: "chronic" },
    { name: "Febrile Seizures", severity: "acute" },
    { name: "Diabetes Type 1", severity: "chronic" },
    { name: "Obesity", severity: "chronic" },
    { name: "Allergic Rhinitis", severity: "mild" },
    { name: "Eczema", severity: "chronic" },
    { name: "Scabies", severity: "acute" },
    { name: "Impetigo", severity: "acute" },
    { name: "Hand Foot Mouth Disease", severity: "acute" },
    { name: "Rotavirus", severity: "acute" },
    { name: "Norovirus", severity: "acute" },
    { name: "RSV Infection", severity: "acute" },
    { name: "Influenza", severity: "acute" },
    { name: "COVID-19", severity: "acute" },
    { name: "Dengue Fever", severity: "acute" },
    { name: "Typhoid Fever", severity: "acute" },
    { name: "Meningitis", severity: "severe" },
    { name: "Encephalitis", severity: "severe" },
    { name: "Growth Delay", severity: "moderate" },
    { name: "Speech Delay", severity: "moderate" },
    { name: "Iron Deficiency Anemia", severity: "moderate" },
    { name: "Vitamin A Deficiency", severity: "moderate" },
    { name: "Constipation", severity: "mild" },
    { name: "GERD", severity: "mild" },
    { name: "Appendicitis", severity: "acute" },
    { name: "Urinary Tract Infection", severity: "acute" }
  ],

Cardiology: [
    { name: "Hypertension", severity: "chronic" },
    { name: "Coronary Artery Disease", severity: "severe" },
    { name: "Myocardial Infarction", severity: "severe" },
    { name: "Heart Failure", severity: "severe" },
    { name: "Arrhythmia", severity: "moderate" },
    { name: "Atrial Fibrillation", severity: "moderate" },
    { name: "Bradycardia", severity: "moderate" },
    { name: "Tachycardia", severity: "moderate" },
    { name: "Cardiomyopathy", severity: "severe" },
    { name: "Valvular Heart Disease", severity: "moderate" },
    { name: "Mitral Valve Prolapse", severity: "mild" },
    { name: "Aortic Stenosis", severity: "severe" },
    { name: "Endocarditis", severity: "severe" },
    { name: "Pericarditis", severity: "acute" },
    { name: "Congenital Heart Disease", severity: "severe" },
    { name: "Angina", severity: "moderate" },
    { name: "Pulmonary Hypertension", severity: "severe" },
    { name: "Deep Vein Thrombosis", severity: "moderate" },
    { name: "Pulmonary Embolism", severity: "severe" },
    { name: "Stroke", severity: "severe" },
    { name: "Atherosclerosis", severity: "chronic" },
    { name: "Hyperlipidemia", severity: "chronic" },
    { name: "Cardiac Arrest", severity: "severe" },
    { name: "Heart Block", severity: "moderate" },
    { name: "Syncope", severity: "mild" },
    { name: "Varicose Veins", severity: "mild" },
    { name: "Peripheral Artery Disease", severity: "moderate" },
    { name: "Rheumatic Heart Disease", severity: "chronic" },
    { name: "Myocarditis", severity: "severe" },
    { name: "Pericardial Effusion", severity: "moderate" }
  ],

ENT: [
{ name: "Otitis Media", severity: "acute" },
{ name: "Chronic Otitis Media", severity: "chronic" },
{ name: "Otitis Externa", severity: "acute" },
{ name: "Hearing Loss", severity: "chronic" },
{ name: "Conductive Hearing Loss", severity: "moderate" },
{ name: "Sensorineural Hearing Loss", severity: "chronic" },
{ name: "Tinnitus", severity: "chronic" },
{ name: "Vertigo", severity: "moderate" },
{ name: "Meniere’s Disease", severity: "chronic" },
{ name: "Labyrinthitis", severity: "acute" },
{ name: "Vestibular Neuritis", severity: "acute" },
{ name: "Sinusitis", severity: "acute" },
{ name: "Chronic Sinusitis", severity: "chronic" },
{ name: "Allergic Rhinitis", severity: "chronic" },
{ name: "Non-Allergic Rhinitis", severity: "chronic" },
{ name: "Nasal Polyps", severity: "chronic" },
{ name: "Deviated Septum", severity: "mild" },
{ name: "Epistaxis", severity: "acute" },
{ name: "Tonsillitis", severity: "acute" },
{ name: "Chronic Tonsillitis", severity: "chronic" },
{ name: "Pharyngitis", severity: "acute" },
{ name: "Laryngitis", severity: "acute" },
{ name: "Vocal Cord Nodules", severity: "moderate" },
{ name: "Vocal Cord Paralysis", severity: "severe" },
{ name: "Sleep Apnea", severity: "severe" },
{ name: "Snoring Disorder", severity: "mild" },
{ name: "Adenoid Hypertrophy", severity: "moderate" },
{ name: "Ear Wax Impaction", severity: "mild" },
{ name: "Foreign Body in Ear", severity: "acute" },
{ name: "Foreign Body in Nose", severity: "acute" },
{ name: "Nasal Fracture", severity: "acute" },
{ name: "Peritonsillar Abscess", severity: "severe" },
{ name: "Throat Cancer", severity: "severe" },
{ name: "Laryngeal Cancer", severity: "severe" },
{ name: "Nasopharyngeal Cancer", severity: "severe" },
{ name: "Globus Sensation", severity: "mild" },
{ name: "Postnasal Drip", severity: "mild" },
{ name: "Cholesteatoma", severity: "severe" },
{ name: "Otitis Media with Effusion", severity: "moderate" },
{ name: "Eustachian Tube Dysfunction", severity: "moderate" },
{ name: "Facial Nerve Palsy", severity: "moderate" },
{ name: "Bell’s Palsy", severity: "acute" },
{ name: "Tracheitis", severity: "acute" },
{ name: "Epiglottitis", severity: "severe" },
{ name: "Rhinosinusitis", severity: "acute" },
{ name: "Nasal Congestion", severity: "mild" },
{ name: "Voice Disorders", severity: "moderate" },
{ name: "Chronic Cough", severity: "moderate" },
{ name: "Thyroid Nodules", severity: "moderate" }
],
Ophthalmology: [
  { name: "Conjunctivitis", severity: "acute" },
  { name: "Allergic Conjunctivitis", severity: "acute" },
  { name: "Dry Eye Syndrome", severity: "chronic" },
  { name: "Cataract", severity: "chronic" },
  { name: "Glaucoma", severity: "severe" },
  { name: "Open-Angle Glaucoma", severity: "chronic" },
  { name: "Angle-Closure Glaucoma", severity: "severe" },
  { name: "Myopia", severity: "mild" },
  { name: "Hyperopia", severity: "mild" },
  { name: "Astigmatism", severity: "mild" },
  { name: "Presbyopia", severity: "mild" },
  { name: "Diabetic Retinopathy", severity: "severe" },
  { name: "Hypertensive Retinopathy", severity: "moderate" },
  { name: "Macular Degeneration", severity: "severe" },
  { name: "Retinal Detachment", severity: "severe" },
  { name: "Uveitis", severity: "moderate" },
  { name: "Anterior Uveitis", severity: "moderate" },
  { name: "Keratitis", severity: "acute" },
  { name: "Corneal Ulcer", severity: "severe" },
  { name: "Blepharitis", severity: "chronic" },
  { name: "Stye", severity: "mild" },
  { name: "Chalazion", severity: "mild" },
  { name: "Eye Trauma", severity: "acute" },
  { name: "Color Blindness", severity: "chronic" },
  { name: "Amblyopia", severity: "chronic" },
  { name: "Strabismus", severity: "moderate" },
  { name: "Optic Neuritis", severity: "moderate" },
  { name: "Night Blindness", severity: "moderate" },
  { name: "Photophobia", severity: "moderate" },
  { name: "Floaters", severity: "mild" },
  { name: "Retinitis Pigmentosa", severity: "chronic" },
  { name: "Vitreous Hemorrhage", severity: "severe" },
  { name: "Eye Allergy", severity: "acute" },
  { name: "Corneal Abrasion", severity: "acute" },
  { name: "Pterygium", severity: "mild" },
  { name: "Pinguecula", severity: "mild" },
  { name: "Lacrimal Duct Obstruction", severity: "moderate" },
  { name: "Dacryocystitis", severity: "acute" },
  { name: "Endophthalmitis", severity: "severe" },
  { name: "Hyphema", severity: "severe" },
  { name: "Orbital Cellulitis", severity: "severe" },
  { name: "Preseptal Cellulitis", severity: "moderate" },
  { name: "Episcleritis", severity: "mild" },
  { name: "Scleritis", severity: "severe" },
  { name: "Lens Dislocation", severity: "severe" },
  { name: "Anisocoria", severity: "moderate" },
  { name: "Diplopia", severity: "moderate" },
  { name: "Eye Strain", severity: "mild" },
  { name: "Computer Vision Syndrome", severity: "mild" }
],
Dentistry: [
  { name: "Dental Caries", severity: "mild" },
  { name: "Early Tooth Decay", severity: "mild" },
  { name: "Advanced Tooth Decay", severity: "moderate" },
  { name: "Gingivitis", severity: "mild" },
  { name: "Periodontitis", severity: "chronic" },
  { name: "Tooth Abscess", severity: "acute" },
  { name: "Periapical Abscess", severity: "acute" },
  { name: "Tooth Sensitivity", severity: "mild" },
  { name: "Broken Tooth", severity: "acute" },
  { name: "Cracked Tooth", severity: "moderate" },
  { name: "Impacted Wisdom Tooth", severity: "moderate" },
  { name: "Malocclusion", severity: "moderate" },
  { name: "Oral Cancer", severity: "severe" },
  { name: "Oral Thrush", severity: "acute" },
  { name: "Halitosis", severity: "mild" },
  { name: "Dry Mouth", severity: "chronic" },
  { name: "TMJ Disorder", severity: "chronic" },
  { name: "Jaw Dislocation", severity: "acute" },
  { name: "Enamel Erosion", severity: "moderate" },
  { name: "Dental Trauma", severity: "acute" },
  { name: "Root Infection", severity: "severe" },
  { name: "Canker Sores", severity: "mild" },
  { name: "Cold Sores", severity: "acute" },
  { name: "Leukoplakia", severity: "moderate" },
  { name: "Dental Plaque", severity: "mild" },
  { name: "Tartar Buildup", severity: "moderate" },
  { name: "Tooth Discoloration", severity: "mild" },
  { name: "Gum Recession", severity: "moderate" },
  { name: "Hyperdontia", severity: "mild" },
  { name: "Hypodontia", severity: "moderate" },
  { name: "Bruxism", severity: "moderate" },
  { name: "Jaw Pain", severity: "moderate" },
  { name: "Oral Ulcers", severity: "mild" },
  { name: "Salivary Gland Infection", severity: "acute" },
  { name: "Sialolithiasis", severity: "moderate" },
  { name: "Burning Mouth Syndrome", severity: "chronic" },
  { name: "Oral Lichen Planus", severity: "chronic" },
  { name: "Pericoronitis", severity: "acute" },
  { name: "Dental Erosion", severity: "moderate" },
  { name: "Fluorosis", severity: "mild" },
  { name: "Pulpitis", severity: "acute" },
  { name: "Necrotic Pulp", severity: "severe" },
  { name: "Alveolar Osteitis", severity: "acute" },
  { name: "Dental Cyst", severity: "moderate" },
  { name: "Oral Fibroma", severity: "mild" },
  { name: "Tongue Tie", severity: "mild" },
  { name: "Glossitis", severity: "moderate" },
  { name: "Angular Cheilitis", severity: "mild" }
],
Orthopedics: [
  { name: "Fracture", severity: "acute" },
  { name: "Open Fracture", severity: "severe" },
  { name: "Closed Fracture", severity: "moderate" },
  { name: "Dislocation", severity: "acute" },
  { name: "Shoulder Dislocation", severity: "acute" },
  { name: "Osteoarthritis", severity: "chronic" },
  { name: "Rheumatoid Arthritis", severity: "chronic" },
  { name: "Osteoporosis", severity: "chronic" },
  { name: "Back Pain", severity: "chronic" },
  { name: "Chronic Low Back Pain", severity: "chronic" },
  { name: "Herniated Disc", severity: "moderate" },
  { name: "Sciatica", severity: "moderate" },
  { name: "Tendonitis", severity: "acute" },
  { name: "Achilles Tendonitis", severity: "acute" },
  { name: "Bursitis", severity: "acute" },
  { name: "ACL Injury", severity: "severe" },
  { name: "PCL Injury", severity: "severe" },
  { name: "Meniscus Tear", severity: "moderate" },
  { name: "Carpal Tunnel Syndrome", severity: "chronic" },
  { name: "Cubital Tunnel Syndrome", severity: "moderate" },
  { name: "Scoliosis", severity: "chronic" },
  { name: "Kyphosis", severity: "chronic" },
  { name: "Lordosis", severity: "chronic" },
  { name: "Bone Tumor", severity: "severe" },
  { name: "Osteosarcoma", severity: "severe" },
  { name: "Joint Infection", severity: "severe" },
  { name: "Septic Arthritis", severity: "severe" },
  { name: "Sprain", severity: "acute" },
  { name: "Muscle Strain", severity: "acute" },
  { name: "Frozen Shoulder", severity: "moderate" },
  { name: "Rotator Cuff Tear", severity: "moderate" },
  { name: "Plantar Fasciitis", severity: "moderate" },
  { name: "Flat Foot", severity: "mild" },
  { name: "Clubfoot", severity: "moderate" },
  { name: "Bone Spur", severity: "moderate" },
  { name: "Gout", severity: "chronic" },
  { name: "Stress Fracture", severity: "moderate" },
  { name: "Hip Fracture", severity: "severe" },
  { name: "Knee Osteoarthritis", severity: "chronic" },
  { name: "Joint Stiffness", severity: "moderate" },
  { name: "Muscle Atrophy", severity: "chronic" },
  { name: "Bone Infection (Osteomyelitis)", severity: "severe" },
  { name: "Trigger Finger", severity: "moderate" },
  { name: "De Quervain Syndrome", severity: "moderate" },
  { name: "Shin Splints", severity: "moderate" },
  { name: "Elbow Pain", severity: "moderate" },
  { name: "Tennis Elbow", severity: "moderate" },
  { name: "Golfer’s Elbow", severity: "moderate" },
  { name: "Joint Dislocation Recurrence", severity: "moderate" }
],
Neurology: [
  { name: "Stroke", severity: "severe" },
  { name: "Ischemic Stroke", severity: "severe" },
  { name: "Hemorrhagic Stroke", severity: "severe" },
  { name: "Epilepsy", severity: "chronic" },
  { name: "Seizures", severity: "acute" },
  { name: "Migraine", severity: "moderate" },
  { name: "Cluster Headache", severity: "moderate" },
  { name: "Tension Headache", severity: "mild" },
  { name: "Parkinson’s Disease", severity: "chronic" },
  { name: "Alzheimer’s Disease", severity: "chronic" },
  { name: "Dementia", severity: "chronic" },
  { name: "Multiple Sclerosis", severity: "chronic" },
  { name: "Brain Tumor", severity: "severe" },
  { name: "Meningitis", severity: "severe" },
  { name: "Encephalitis", severity: "severe" },
  { name: "Peripheral Neuropathy", severity: "chronic" },
  { name: "Diabetic Neuropathy", severity: "chronic" },
  { name: "Bell’s Palsy", severity: "acute" },
  { name: "Trigeminal Neuralgia", severity: "moderate" },
  { name: "ALS", severity: "severe" },
  { name: "Guillain-Barre Syndrome", severity: "severe" },
  { name: "Cerebral Palsy", severity: "chronic" },
  { name: "Spinal Cord Injury", severity: "severe" },
  { name: "Vertigo", severity: "moderate" },
  { name: "Syncope", severity: "mild" },
  { name: "Neuropathic Pain", severity: "chronic" },
  { name: "Myasthenia Gravis", severity: "chronic" },
  { name: "Brain Abscess", severity: "severe" },
  { name: "Hydrocephalus", severity: "severe" },
  { name: "Neurodegenerative Disorders", severity: "chronic" },
  { name: "Restless Leg Syndrome", severity: "moderate" },
  { name: "Ataxia", severity: "moderate" },
  { name: "Neuralgia", severity: "moderate" },
  { name: "Cranial Nerve Disorders", severity: "moderate" },
  { name: "Sleep Disorders", severity: "moderate" },
  { name: "Narcolepsy", severity: "moderate" },
  { name: "Brain Hemorrhage", severity: "severe" },
  { name: "Subdural Hematoma", severity: "severe" },
  { name: "Concussion", severity: "moderate" },
  { name: "Post-Concussion Syndrome", severity: "moderate" },
  { name: "Spinal Stenosis", severity: "moderate" },
  { name: "Radiculopathy", severity: "moderate" },
  { name: "Motor Neuron Disease", severity: "severe" },
  { name: "Neuromuscular Disorders", severity: "chronic" },
  { name: "Dystonia", severity: "moderate" },
  { name: "Tremor", severity: "mild" },
  { name: "Chronic Headache", severity: "moderate" }
],
Psychiatry: [
  { name: "Depression", severity: "chronic" },
  { name: "Major Depressive Disorder", severity: "severe" },
  { name: "Anxiety Disorder", severity: "chronic" },
  { name: "Generalized Anxiety Disorder", severity: "chronic" },
  { name: "Panic Disorder", severity: "acute" },
  { name: "Phobias", severity: "moderate" },
  { name: "Social Anxiety", severity: "moderate" },
  { name: "OCD", severity: "chronic" },
  { name: "PTSD", severity: "chronic" },
  { name: "Bipolar Disorder", severity: "chronic" },
  { name: "Schizophrenia", severity: "severe" },
  { name: "Schizoaffective Disorder", severity: "severe" },
  { name: "Eating Disorders", severity: "severe" },
  { name: "Anorexia", severity: "severe" },
  { name: "Bulimia", severity: "severe" },
  { name: "ADHD", severity: "chronic" },
  { name: "Autism Spectrum Disorder", severity: "chronic" },
  { name: "Insomnia", severity: "moderate" },
  { name: "Sleep Disorders", severity: "moderate" },
  { name: "Substance Abuse", severity: "severe" },
  { name: "Alcohol Dependence", severity: "severe" },
  { name: "Drug Addiction", severity: "severe" },
  { name: "Personality Disorders", severity: "chronic" },
  { name: "Borderline Personality Disorder", severity: "severe" },
  { name: "Narcissistic Personality Disorder", severity: "moderate" },
  { name: "Antisocial Personality Disorder", severity: "severe" },
  { name: "Dementia", severity: "chronic" },
  { name: "Delirium", severity: "acute" },
  { name: "Self-Harm Behavior", severity: "severe" },
  { name: "Suicidal Ideation", severity: "severe" },
  { name: "Stress Disorder", severity: "moderate" },
  { name: "Adjustment Disorder", severity: "moderate" },
  { name: "Seasonal Affective Disorder", severity: "moderate" },
  { name: "Postpartum Depression", severity: "severe" },
  { name: "Panic Attacks", severity: "acute" },
  { name: "Emotional Instability", severity: "moderate" },
  { name: "Hallucinations", severity: "severe" },
  { name: "Delusions", severity: "severe" },
  { name: "Paranoia", severity: "moderate" },
  { name: "Psychosis", severity: "severe" },
  { name: "Mood Disorders", severity: "chronic" },
  { name: "Behavioral Disorders", severity: "moderate" },
  { name: "Impulse Control Disorder", severity: "moderate" },
  { name: "Conduct Disorder", severity: "moderate" },
  { name: "Oppositional Defiant Disorder", severity: "moderate" },
  { name: "Sleepwalking", severity: "mild" },
  { name: "Night Terrors", severity: "moderate" }
],
Urology: [
  { name: "Urinary Tract Infection", severity: "acute" },
  { name: "Recurrent UTI", severity: "chronic" },
  { name: "Kidney Stones", severity: "moderate" },
  { name: "Bladder Stones", severity: "moderate" },
  { name: "Chronic Kidney Disease", severity: "severe" },
  { name: "Acute Kidney Injury", severity: "acute" },
  { name: "Prostate Enlargement", severity: "chronic" },
  { name: "Benign Prostatic Hyperplasia", severity: "chronic" },
  { name: "Prostate Cancer", severity: "severe" },
  { name: "Bladder Cancer", severity: "severe" },
  { name: "Kidney Cancer", severity: "severe" },
  { name: "Hematuria", severity: "moderate" },
  { name: "Urinary Incontinence", severity: "moderate" },
  { name: "Stress Incontinence", severity: "moderate" },
  { name: "Urge Incontinence", severity: "moderate" },
  { name: "Erectile Dysfunction", severity: "moderate" },
  { name: "Male Infertility", severity: "moderate" },
  { name: "Hydronephrosis", severity: "severe" },
  { name: "Cystitis", severity: "acute" },
  { name: "Interstitial Cystitis", severity: "chronic" },
  { name: "Pyelonephritis", severity: "severe" },
  { name: "Urethritis", severity: "acute" },
  { name: "Testicular Torsion", severity: "severe" },
  { name: "Varicocele", severity: "moderate" },
  { name: "Hydrocele", severity: "moderate" },
  { name: "Epididymitis", severity: "acute" },
  { name: "Orchitis", severity: "acute" },
  { name: "Bladder Infection", severity: "acute" },
  { name: "Neurogenic Bladder", severity: "chronic" },
  { name: "Urinary Retention", severity: "severe" },
  { name: "Frequent Urination", severity: "mild" },
  { name: "Nocturia", severity: "moderate" },
  { name: "Dysuria", severity: "moderate" },
  { name: "Kidney Failure", severity: "severe" },
  { name: "Renal Colic", severity: "severe" },
  { name: "Bladder Outlet Obstruction", severity: "severe" },
  { name: "Ureteral Obstruction", severity: "severe" },
  { name: "Urethral Stricture", severity: "moderate" },
  { name: "Testicular Cancer", severity: "severe" },
  { name: "Penile Cancer", severity: "severe" },
  { name: "Sexually Transmitted Infections", severity: "moderate" },
  { name: "Chlamydia", severity: "moderate" },
  { name: "Gonorrhea", severity: "moderate" },
  { name: "Syphilis", severity: "severe" },
  { name: "HPV Infection", severity: "chronic" },
  { name: "Genital Herpes", severity: "chronic" }
],
Gynecology: [
  { name: "PCOS", severity: "chronic" },
  { name: "Endometriosis", severity: "chronic" },
  { name: "Uterine Fibroids", severity: "moderate" },
  { name: "Ovarian Cysts", severity: "moderate" },
  { name: "Infertility", severity: "chronic" },
  { name: "Menstrual Disorders", severity: "moderate" },
  { name: "Amenorrhea", severity: "moderate" },
  { name: "Dysmenorrhea", severity: "moderate" },
  { name: "Menorrhagia", severity: "moderate" },
  { name: "Pelvic Inflammatory Disease", severity: "acute" },
  { name: "Cervical Cancer", severity: "severe" },
  { name: "Ovarian Cancer", severity: "severe" },
  { name: "Endometrial Cancer", severity: "severe" },
  { name: "Vaginitis", severity: "acute" },
  { name: "Bacterial Vaginosis", severity: "acute" },
  { name: "Yeast Infection", severity: "acute" },
  { name: "Sexually Transmitted Diseases", severity: "moderate" },
  { name: "HPV Infection", severity: "chronic" },
  { name: "Herpes Infection", severity: "chronic" },
  { name: "Ectopic Pregnancy", severity: "severe" },
  { name: "Miscarriage", severity: "severe" },
  { name: "Menopause Symptoms", severity: "moderate" },
  { name: "Postmenopausal Bleeding", severity: "severe" },
  { name: "Postpartum Depression", severity: "severe" },
  { name: "Placenta Previa", severity: "severe" },
  { name: "Placental Abruption", severity: "severe" },
  { name: "Pre-eclampsia", severity: "severe" },
  { name: "Eclampsia", severity: "severe" },
  { name: "Gestational Diabetes", severity: "moderate" },
  { name: "Vaginal Dryness", severity: "mild" },
  { name: "Dyspareunia", severity: "moderate" },
  { name: "Uterine Prolapse", severity: "moderate" },
  { name: "Cervicitis", severity: "acute" },
  { name: "Ovarian Torsion", severity: "severe" },
  { name: "Endometrial Hyperplasia", severity: "moderate" },
  { name: "Hormonal Imbalance", severity: "moderate" },
  { name: "Breast Cysts", severity: "moderate" },
  { name: "Mastitis", severity: "acute" },
  { name: "Breast Cancer", severity: "severe" },
  { name: "Fibrocystic Breast Disease", severity: "moderate" },
  { name: "Galactorrhea", severity: "moderate" },
  { name: "Vulvodynia", severity: "moderate" },
  { name: "Bartholin Cyst", severity: "moderate" },
  { name: "Bartholin Abscess", severity: "acute" },
  { name: "Pelvic Pain", severity: "moderate" },
  { name: "Chronic Pelvic Pain", severity: "chronic" }
],
Dermatology: [
  { name: "Acne Vulgaris", severity: "mild" },
  { name: "Severe Acne", severity: "moderate" },
  { name: "Eczema", severity: "chronic" },
  { name: "Atopic Dermatitis", severity: "chronic" },
  { name: "Contact Dermatitis", severity: "acute" },
  { name: "Seborrheic Dermatitis", severity: "chronic" },
  { name: "Psoriasis", severity: "chronic" },
  { name: "Psoriatic Arthritis", severity: "chronic" },
  { name: "Vitiligo", severity: "chronic" },
  { name: "Rosacea", severity: "chronic" },
  { name: "Urticaria (Hives)", severity: "acute" },
  { name: "Chronic Urticaria", severity: "chronic" },
  { name: "Fungal Skin Infection", severity: "acute" },
  { name: "Tinea Corporis", severity: "acute" },
  { name: "Tinea Pedis (Athlete’s Foot)", severity: "acute" },
  { name: "Tinea Cruris", severity: "acute" },
  { name: "Onychomycosis (Nail Fungus)", severity: "chronic" },
  { name: "Bacterial Skin Infection", severity: "acute" },
  { name: "Impetigo", severity: "acute" },
  { name: "Cellulitis", severity: "acute" },
  { name: "Abscess", severity: "acute" },
  { name: "Boils (Furuncles)", severity: "acute" },
  { name: "Carbuncles", severity: "acute" },
  { name: "Folliculitis", severity: "acute" },
  { name: "Herpes Simplex", severity: "acute" },
  { name: "Herpes Zoster (Shingles)", severity: "acute" },
  { name: "Molluscum Contagiosum", severity: "acute" },
  { name: "Viral Warts", severity: "mild" },
  { name: "Scabies", severity: "acute" },
  { name: "Pediculosis (Lice)", severity: "acute" },
  { name: "Melasma", severity: "mild" },
  { name: "Hyperpigmentation", severity: "mild" },
  { name: "Hypopigmentation", severity: "mild" },
  { name: "Sunburn", severity: "acute" },
  { name: "Photosensitivity", severity: "chronic" },
  { name: "Skin Allergy", severity: "acute" },
  { name: "Drug Rash", severity: "acute" },
  { name: "Erythema Multiforme", severity: "acute" },
  { name: "Lichen Planus", severity: "chronic" },
  { name: "Pityriasis Rosea", severity: "acute" },
  { name: "Hidradenitis Suppurativa", severity: "chronic" },
  { name: "Pruritus (Itching)", severity: "chronic" },
  { name: "Ichthyosis", severity: "chronic" },
  { name: "Keloid", severity: "chronic" },
  { name: "Hypertrophic Scar", severity: "chronic" },
  { name: "Skin Tags", severity: "mild" },
  { name: "Dermatofibroma", severity: "mild" },
  { name: "Skin Cyst", severity: "mild" },
  { name: "Lipoma", severity: "mild" },
  { name: "Basal Cell Carcinoma", severity: "severe" },
  { name: "Squamous Cell Carcinoma", severity: "severe" },
  { name: "Melanoma", severity: "severe" },
  { name: "Actinic Keratosis", severity: "moderate" },
  { name: "Skin Ulcer", severity: "moderate" },
  { name: "Intertrigo", severity: "acute" },
  { name: "Angioedema", severity: "acute" }
]

};


// Wrapper for diseases data - using existing diseasesBySpecialty
// Maps severity levels for color coding:
// - acute/severe → red (#dc2626)
// - chronic/moderate → yellow (#ca8a04)  
// - mild → green (#15803d)

function getDiseasesBySpecialty(specialty) {
    if (diseasesBySpecialty && diseasesBySpecialty[specialty]) {
        return diseasesBySpecialty[specialty];
    }
    return [];
}

function searchDiseases(searchTerm, specialty) {
    const diseases = getDiseasesBySpecialty(specialty);
    const term = searchTerm.toLowerCase();
    
    return diseases
        .filter(d => d.name.toLowerCase().includes(term))
        .map(d => ({
            id: d.name.replace(/\s+/g, '_').toLowerCase(),
            name: d.name,
            severity: mappingSeverityToUILevel(d.severity)
        }));
}

// Map disease severity to UI severity levels (severe/moderate/mild)
function mappingSeverityToUILevel(dbSeverity) {
    const severityMap = {
        'acute': 'severe',      // acute → red
        'severe': 'severe',     // severe → red
        'chronic': 'moderate',  // chronic → yellow
        'moderate': 'moderate', // moderate → yellow
        'mild': 'mild'          // mild → green
    };
    return severityMap[dbSeverity] || 'moderate';
}

