const diseasesBySpecialty = {

  Vaccination: [
    { name: "Influenza", severity: "acute" },
    { name: "COVID-19", severity: "acute" },
    { name: "Measles", severity: "acute" },
    { name: "Mumps", severity: "acute" },
    { name: "Rubella", severity: "acute" },
    { name: "Polio", severity: "chronic" },
    { name: "Hepatitis A", severity: "acute" },
    { name: "Hepatitis B", severity: "chronic" },
    { name: "Hepatitis C", severity: "chronic" },
    { name: "Tetanus", severity: "acute" },
    { name: "Diphtheria", severity: "acute" },
    { name: "Pertussis", severity: "acute" },
    { name: "Chickenpox", severity: "acute" },
    { name: "HPV Infection", severity: "chronic" },
    { name: "Pneumococcal Disease", severity: "acute" },
    { name: "Meningococcal Disease", severity: "acute" },
    { name: "Rotavirus", severity: "acute" },
    { name: "Tuberculosis", severity: "chronic" },
    { name: "Rabies", severity: "acute" },
    { name: "Typhoid Fever", severity: "acute" },
    { name: "Cholera", severity: "acute" },
    { name: "Yellow Fever", severity: "acute" },
    { name: "Japanese Encephalitis", severity: "acute" },
    { name: "Shingles", severity: "acute" },
    { name: "Haemophilus Influenzae", severity: "acute" },
    { name: "Smallpox", severity: "acute" },
    { name: "Anthrax", severity: "acute" },
    { name: "Ebola", severity: "acute" },
    { name: "Zika Virus", severity: "acute" },
    { name: "Dengue Fever", severity: "acute" },
    { name: "Malaria", severity: "acute" },
    { name: "Hib Infection", severity: "acute" },
    { name: "Varicella", severity: "acute" },
    { name: "H1N1", severity: "acute" },
    { name: "RSV Infection", severity: "acute" },
    { name: "Norovirus", severity: "acute" },
    { name: "Tick-borne Encephalitis", severity: "acute" },
    { name: "Monkeypox", severity: "acute" },
    { name: "West Nile Virus", severity: "acute" },
    { name: "Plague", severity: "acute" },
    { name: "Leptospirosis", severity: "acute" },
    { name: "Q Fever", severity: "acute" },
    { name: "Brucellosis", severity: "chronic" },
    { name: "Hepatitis D", severity: "chronic" },
    { name: "Hepatitis E", severity: "acute" },
    { name: "Measles Complications", severity: "acute" },
    { name: "Mumps Orchitis", severity: "acute" },
    { name: "Rubella Pregnancy Risk", severity: "acute" },
    { name: "Post Polio Syndrome", severity: "chronic" }
  ],

Dermatology: [
    { name: "Acne Vulgaris", severity: "mild" },
    { name: "Eczema", severity: "chronic" },
    { name: "Psoriasis", severity: "chronic" },
    { name: "Vitiligo", severity: "chronic" },
    { name: "Rosacea", severity: "chronic" },
    { name: "Urticaria", severity: "acute" },
    { name: "Contact Dermatitis", severity: "acute" },
    { name: "Seborrheic Dermatitis", severity: "chronic" },
    { name: "Fungal Skin Infection", severity: "acute" },
    { name: "Bacterial Skin Infection", severity: "acute" },
    { name: "Viral Warts", severity: "mild" },
    { name: "Melasma", severity: "mild" },
    { name: "Skin Tags", severity: "mild" },
    { name: "Alopecia Areata", severity: "chronic" },
    { name: "Scabies", severity: "acute" },
    { name: "Impetigo", severity: "acute" },
    { name: "Cellulitis", severity: "acute" },
    { name: "Herpes Simplex", severity: "acute" },
    { name: "Herpes Zoster", severity: "acute" },
    { name: "Basal Cell Carcinoma", severity: "chronic" },
    { name: "Squamous Cell Carcinoma", severity: "chronic" },
    { name: "Melanoma", severity: "chronic" },
    { name: "Lichen Planus", severity: "chronic" },
    { name: "Pityriasis Rosea", severity: "acute" },
    { name: "Hidradenitis Suppurativa", severity: "chronic" },
    { name: "Nail Fungus", severity: "chronic" },
    { name: "Sunburn", severity: "acute" },
    { name: "Hyperpigmentation", severity: "mild" },
    { name: "Molluscum Contagiosum", severity: "acute" },
    { name: "Psoriatic Arthritis", severity: "chronic" },
    { name: "Atopic Dermatitis", severity: "chronic" },
    { name: "Skin Allergy", severity: "acute" },
    { name: "Drug Rash", severity: "acute" },
    { name: "Erythema Multiforme", severity: "acute" },
    { name: "Photosensitivity", severity: "chronic" },
    { name: "Skin Ulcer", severity: "acute" },
    { name: "Keloid", severity: "chronic" },
    { name: "Hypertrophic Scar", severity: "chronic" },
    { name: "Intertrigo", severity: "acute" },
    { name: "Boils", severity: "acute" },
    { name: "Abscess", severity: "acute" },
    { name: "Folliculitis", severity: "acute" },
    { name: "Pruritus", severity: "chronic" },
    { name: "Ichthyosis", severity: "chronic" },
    { name: "Skin Cyst", severity: "mild" },
    { name: "Dermatofibroma", severity: "mild" },
    { name: "Angioedema", severity: "acute" }
  ],
Psychiatry: [
    { name: "Depression", severity: "chronic" },
    { name: "Major Depressive Disorder", severity: "chronic" },
    { name: "Anxiety Disorder", severity: "chronic" },
    { name: "Generalized Anxiety Disorder", severity: "chronic" },
    { name: "Panic Disorder", severity: "acute" },
    { name: "Bipolar Disorder", severity: "chronic" },
    { name: "Schizophrenia", severity: "chronic" },
    { name: "Obsessive Compulsive Disorder", severity: "chronic" },
    { name: "Post Traumatic Stress Disorder", severity: "chronic" },
    { name: "Social Anxiety Disorder", severity: "chronic" },
    { name: "Phobia", severity: "mild" },
    { name: "Insomnia", severity: "chronic" },
    { name: "Sleep Disorder", severity: "chronic" },
    { name: "Eating Disorder", severity: "chronic" },
    { name: "Anorexia Nervosa", severity: "chronic" },
    { name: "Bulimia Nervosa", severity: "chronic" },
    { name: "ADHD", severity: "chronic" },
    { name: "Autism Spectrum Disorder", severity: "chronic" },
    { name: "Dementia", severity: "chronic" },
    { name: "Alzheimer’s Disease", severity: "chronic" },
    { name: "Delusional Disorder", severity: "chronic" },
    { name: "Psychosis", severity: "acute" },
    { name: "Substance Abuse", severity: "chronic" },
    { name: "Alcohol Dependence", severity: "chronic" },
    { name: "Drug Addiction", severity: "chronic" },
    { name: "Personality Disorder", severity: "chronic" },
    { name: "Borderline Personality Disorder", severity: "chronic" },
    { name: "Antisocial Personality Disorder", severity: "chronic" },
    { name: "Stress Disorder", severity: "acute" },
    { name: "Adjustment Disorder", severity: "acute" },
    { name: "Somatic Symptom Disorder", severity: "chronic" },
    { name: "Conversion Disorder", severity: "acute" },
    { name: "Mood Disorder", severity: "chronic" },
    { name: "Impulse Control Disorder", severity: "chronic" },
    { name: "Conduct Disorder", severity: "chronic" },
    { name: "Tourette Syndrome", severity: "chronic" },
    { name: "Catatonia", severity: "acute" },
    { name: "Paranoid Disorder", severity: "chronic" },
    { name: "Hallucinations", severity: "acute" },
    { name: "Memory Disorder", severity: "chronic" },
    { name: "Aggressive Behavior", severity: "acute" },
    { name: "Suicidal Ideation", severity: "acute" },
    { name: "Self Harm Behavior", severity: "acute" },
    { name: "Sleepwalking", severity: "mild" },
    { name: "Night Terrors", severity: "acute" },
    { name: "Seasonal Affective Disorder", severity: "chronic" }
],
Pediatrics: [
    { name: "Common Cold", severity: "acute" },
    { name: "Influenza", severity: "acute" },
    { name: "Asthma", severity: "chronic" },
    { name: "Bronchiolitis", severity: "acute" },
    { name: "Pneumonia", severity: "acute" },
    { name: "Tonsillitis", severity: "acute" },
    { name: "Otitis Media", severity: "acute" },
    { name: "Gastroenteritis", severity: "acute" },
    { name: "Diarrhea", severity: "acute" },
    { name: "Dehydration", severity: "acute" },
    { name: "Measles", severity: "acute" },
    { name: "Chickenpox", severity: "acute" },
    { name: "Mumps", severity: "acute" },
    { name: "Rubella", severity: "acute" },
    { name: "Whooping Cough", severity: "acute" },
    { name: "Croup", severity: "acute" },
    { name: "Hand Foot Mouth Disease", severity: "acute" },
    { name: "Febrile Seizure", severity: "acute" },
    { name: "Epilepsy", severity: "chronic" },
    { name: "Autism", severity: "chronic" },
    { name: "ADHD", severity: "chronic" },
    { name: "Down Syndrome", severity: "chronic" },
    { name: "Congenital Heart Disease", severity: "chronic" },
    { name: "Neonatal Jaundice", severity: "acute" },
    { name: "Failure to Thrive", severity: "chronic" },
    { name: "Malnutrition", severity: "chronic" },
    { name: "Iron Deficiency Anemia", severity: "chronic" },
    { name: "Constipation", severity: "chronic" },
    { name: "Urinary Tract Infection", severity: "acute" },
    { name: "Skin Rash", severity: "acute" },
    { name: "Food Allergy", severity: "acute" },
    { name: "Lactose Intolerance", severity: "chronic" },
    { name: "Vomiting", severity: "acute" },
    { name: "Growth Delay", severity: "chronic" },
    { name: "Developmental Delay", severity: "chronic" },
    { name: "Intestinal Worms", severity: "acute" },
    { name: "Head Lice", severity: "acute" },
    { name: "Nose Bleeding", severity: "acute" },
    { name: "Anemia", severity: "chronic" },
    { name: "Sepsis", severity: "acute" },
    { name: "Rickets", severity: "chronic" },
    { name: "Neonatal Infection", severity: "acute" },
    { name: "Sudden Infant Death Risk", severity: "acute" }
],
Orthopedics: [
    { name: "Bone Fracture", severity: "acute" },
    { name: "Stress Fracture", severity: "chronic" },
    { name: "Osteoarthritis", severity: "chronic" },
    { name: "Rheumatoid Arthritis", severity: "chronic" },
    { name: "Osteoporosis", severity: "chronic" },
    { name: "Low Back Pain", severity: "chronic" },
    { name: "Sciatica", severity: "chronic" },
    { name: "Herniated Disc", severity: "chronic" },
    { name: "Scoliosis", severity: "chronic" },
    { name: "Kyphosis", severity: "chronic" },
    { name: "Ligament Tear", severity: "acute" },
    { name: "Meniscus Injury", severity: "acute" },
    { name: "Rotator Cuff Injury", severity: "acute" },
    { name: "Frozen Shoulder", severity: "chronic" },
    { name: "Carpal Tunnel Syndrome", severity: "chronic" },
    { name: "Tennis Elbow", severity: "chronic" },
    { name: "Golfer’s Elbow", severity: "chronic" },
    { name: "Plantar Fasciitis", severity: "chronic" },
    { name: "Achilles Tendon Rupture", severity: "acute" },
    { name: "Hip Dislocation", severity: "acute" },
    { name: "Knee Dislocation", severity: "acute" },
    { name: "Joint Infection", severity: "acute" },
    { name: "Bone Infection", severity: "acute" },
    { name: "Spinal Stenosis", severity: "chronic" },
    { name: "Ankylosing Spondylitis", severity: "chronic" },
    { name: "Gout", severity: "chronic" },
    { name: "Bursitis", severity: "chronic" },
    { name: "Tendonitis", severity: "chronic" },
    { name: "Flat Foot", severity: "chronic" },
    { name: "Club Foot", severity: "chronic" },
    { name: "Bone Tumor", severity: "chronic" },
    { name: "Joint Stiffness", severity: "chronic" },
    { name: "Neck Pain", severity: "chronic" },
    { name: "Spinal Injury", severity: "acute" },
    { name: "Crush Injury", severity: "acute" },
    { name: "Post Traumatic Arthritis", severity: "chronic" },
    { name: "Joint Effusion", severity: "acute" },
    { name: "Osteomyelitis", severity: "acute" },
    { name: "Muscle Strain", severity: "acute" },
    { name: "Muscle Tear", severity: "acute" },
    { name: "Shoulder Impingement", severity: "chronic" },
    { name: "Hip Arthritis", severity: "chronic" },
    { name: "Knee Arthritis", severity: "chronic" }
],
"General Surgery": [
    { name: "Appendicitis", severity: "acute" },
    { name: "Hernia", severity: "chronic" },
    { name: "Strangulated Hernia", severity: "acute" },
    { name: "Gallstones", severity: "chronic" },
    { name: "Cholecystitis", severity: "acute" },
    { name: "Pancreatitis", severity: "acute" },
    { name: "Intestinal Obstruction", severity: "acute" },
    { name: "Peritonitis", severity: "acute" },
    { name: "Abscess", severity: "acute" },
    { name: "Hemorrhoids", severity: "chronic" },
    { name: "Anal Fissure", severity: "acute" },
    { name: "Anal Fistula", severity: "chronic" },
    { name: "Pilonidal Sinus", severity: "chronic" },
    { name: "Colon Cancer", severity: "chronic" },
    { name: "Rectal Cancer", severity: "chronic" },
    { name: "Breast Lump", severity: "mild" },
    { name: "Breast Cancer", severity: "chronic" },
    { name: "Mastitis", severity: "acute" },
    { name: "Thyroid Nodule", severity: "chronic" },
    { name: "Goiter", severity: "chronic" },
    { name: "Varicose Veins", severity: "chronic" },
    { name: "Deep Vein Thrombosis", severity: "acute" },
    { name: "Diabetic Foot", severity: "chronic" },
    { name: "Soft Tissue Tumor", severity: "chronic" },
    { name: "Lipoma", severity: "mild" },
    { name: "Lymphadenitis", severity: "acute" },
    { name: "Splenomegaly", severity: "chronic" },
    { name: "Gastric Ulcer", severity: "chronic" },
    { name: "Perforated Ulcer", severity: "acute" },
    { name: "Bowel Perforation", severity: "acute" },
    { name: "Intestinal Ischemia", severity: "acute" },
    { name: "Burn Injury", severity: "acute" },
    { name: "Trauma Injury", severity: "acute" },
    { name: "Wound Infection", severity: "acute" },
    { name: "Postoperative Infection", severity: "acute" },
    { name: "Postoperative Bleeding", severity: "acute" },
    { name: "Sepsis", severity: "acute" },
    { name: "Obesity", severity: "chronic" },
    { name: "Adhesions", severity: "chronic" },
    { name: "Fistula", severity: "chronic" },
    { name: "Bowel Obstruction Adhesive", severity: "acute" },
    { name: "Necrotizing Fasciitis", severity: "acute" },
    { name: "Hydrocele", severity: "chronic" },
    { name: "Varicocele", severity: "chronic" },
    { name: "Inguinal Pain", severity: "mild" }
],
Dentistry: [
    { name: "Dental Caries", severity: "mild" },
    { name: "Gingivitis", severity: "mild" },
    { name: "Periodontitis", severity: "chronic" },
    { name: "Tooth Abscess", severity: "acute" },
    { name: "Periapical Abscess", severity: "acute" },
    { name: "Tooth Sensitivity", severity: "mild" },
    { name: "Impacted Tooth", severity: "chronic" },
    { name: "Wisdom Tooth Pain", severity: "acute" },
    { name: "Oral Ulcer", severity: "acute" },
    { name: "Oral Thrush", severity: "acute" },
    { name: "Bad Breath", severity: "mild" },
    { name: "Broken Tooth", severity: "acute" },
    { name: "Dental Trauma", severity: "acute" },
    { name: "Jaw Pain", severity: "chronic" },
    { name: "TMJ Disorder", severity: "chronic" },
    { name: "Bruxism", severity: "chronic" },
    { name: "Dry Mouth", severity: "chronic" },
    { name: "Bleeding Gums", severity: "mild" },
    { name: "Gum Recession", severity: "chronic" },
    { name: "Loose Teeth", severity: "chronic" },
    { name: "Dental Cyst", severity: "chronic" },
    { name: "Root Canal Infection", severity: "acute" },
    { name: "Tooth Discoloration", severity: "mild" },
    { name: "Enamel Erosion", severity: "chronic" },
    { name: "Dental Plaque", severity: "mild" },
    { name: "Tartar Buildup", severity: "mild" },
    { name: "Orthodontic Pain", severity: "acute" },
    { name: "Dental Infection", severity: "acute" },
    { name: "Facial Swelling Dental", severity: "acute" },
    { name: "Oral Cancer", severity: "chronic" },
    { name: "Pericoronitis", severity: "acute" },
    { name: "Cracked Tooth Syndrome", severity: "chronic" },
    { name: "Dental Hypersensitivity", severity: "mild" },
    { name: "Mouth Breathing", severity: "mild" },
    { name: "Gum Abscess", severity: "acute" },
    { name: "Dental Erosion", severity: "chronic" },
    { name: "Malocclusion", severity: "chronic" },
    { name: "Jaw Infection", severity: "acute" },
    { name: "Oral Leukoplakia", severity: "chronic" },
    { name: "Aphthous Ulcer", severity: "acute" },
    { name: "Dental Pain", severity: "acute" },
    { name: "Inflamed Gums", severity: "mild" },
    { name: "Dental Pulpitis", severity: "acute" },
    { name: "Dental Fistula", severity: "chronic" },
    { name: "Post Extraction Pain", severity: "acute" }
],
Obstetrics: [
    { name: "Normal Pregnancy", severity: "mild" },
    { name: "High Risk Pregnancy", severity: "chronic" },
    { name: "Gestational Diabetes", severity: "chronic" },
    { name: "Gestational Hypertension", severity: "chronic" },
    { name: "Preeclampsia", severity: "acute" },
    { name: "Eclampsia", severity: "acute" },
    { name: "Preterm Labor", severity: "acute" },
    { name: "Post Term Pregnancy", severity: "chronic" },
    { name: "Placenta Previa", severity: "acute" },
    { name: "Placental Abruption", severity: "acute" },
    { name: "Ectopic Pregnancy", severity: "acute" },
    { name: "Miscarriage", severity: "acute" },
    { name: "Stillbirth", severity: "acute" },
    { name: "Anemia in Pregnancy", severity: "chronic" },
    { name: "Hyperemesis Gravidarum", severity: "acute" },
    { name: "Rh Incompatibility", severity: "chronic" },
    { name: "Multiple Pregnancy", severity: "chronic" },
    { name: "IUGR", severity: "chronic" },
    { name: "Oligohydramnios", severity: "chronic" },
    { name: "Polyhydramnios", severity: "chronic" },
    { name: "PROM", severity: "acute" },
    { name: "Postpartum Hemorrhage", severity: "acute" },
    { name: "Postpartum Infection", severity: "acute" },
    { name: "Uterine Rupture", severity: "acute" },
    { name: "Labor Pain", severity: "acute" },
    { name: "Fetal Distress", severity: "acute" },
    { name: "Cord Prolapse", severity: "acute" },
    { name: "Placental Insufficiency", severity: "chronic" },
    { name: "Cesarean Complication", severity: "acute" },
    { name: "Postpartum Depression", severity: "chronic" },
    { name: "Gestational Thrombosis", severity: "acute" },
    { name: "Pregnancy Induced Anemia", severity: "chronic" },
    { name: "Obstructed Labor", severity: "acute" },
    { name: "Prolonged Labor", severity: "acute" },
    { name: "Uterine Infection", severity: "acute" },
    { name: "Placental Retention", severity: "acute" },
    { name: "Pregnancy Back Pain", severity: "mild" },
    { name: "Pregnancy Edema", severity: "mild" },
    { name: "Gestational Hypothyroidism", severity: "chronic" },
    { name: "Gestational Hyperthyroidism", severity: "chronic" },
    { name: "Pre Labor Rupture", severity: "acute" },
    { name: "Fetal Growth Delay", severity: "chronic" }
],
Gynecology: [
    { name: "Polycystic Ovary Syndrome", severity: "chronic" },
    { name: "Endometriosis", severity: "chronic" },
    { name: "Uterine Fibroids", severity: "chronic" },
    { name: "Ovarian Cyst", severity: "chronic" },
    { name: "Pelvic Inflammatory Disease", severity: "acute" },
    { name: "Vaginitis", severity: "acute" },
    { name: "Vulvitis", severity: "acute" },
    { name: "Cervicitis", severity: "acute" },
    { name: "Cervical Cancer", severity: "chronic" },
    { name: "Ovarian Cancer", severity: "chronic" },
    { name: "Endometrial Cancer", severity: "chronic" },
    { name: "Menstrual Irregularities", severity: "chronic" },
    { name: "Amenorrhea", severity: "chronic" },
    { name: "Menorrhagia", severity: "chronic" },
    { name: "Dysmenorrhea", severity: "chronic" },
    { name: "Postmenopausal Bleeding", severity: "acute" },
    { name: "Infertility", severity: "chronic" },
    { name: "Pelvic Pain", severity: "chronic" },
    { name: "Uterine Prolapse", severity: "chronic" },
    { name: "Vaginal Prolapse", severity: "chronic" },
    { name: "Dyspareunia", severity: "chronic" },
    { name: "Menopause", severity: "chronic" },
    { name: "Hormonal Imbalance", severity: "chronic" },
    { name: "Sexually Transmitted Disease", severity: "acute" },
    { name: "Genital Warts", severity: "chronic" },
    { name: "Vaginal Dryness", severity: "chronic" },
    { name: "Bartholin Cyst", severity: "acute" },
    { name: "Ovarian Torsion", severity: "acute" },
    { name: "Endometritis", severity: "acute" },
    { name: "Vaginal Bleeding", severity: "acute" },
    { name: "Cervical Polyp", severity: "mild" },
    { name: "Uterine Adhesions", severity: "chronic" },
    { name: "Pelvic Abscess", severity: "acute" },
    { name: "Recurrent Vaginal Infection", severity: "chronic" },
    { name: "Premenstrual Syndrome", severity: "chronic" },
    { name: "Premenstrual Dysphoric Disorder", severity: "chronic" },
    { name: "Ovarian Failure", severity: "chronic" },
    { name: "Genital Ulcer", severity: "acute" },
    { name: "Cervical Erosion", severity: "chronic" },
    { name: "Pelvic Congestion Syndrome", severity: "chronic" },
    { name: "Vulvar Pain Syndrome", severity: "chronic" }
],
Fertility: [
    { name: "Male Infertility", severity: "chronic" },
    { name: "Female Infertility", severity: "chronic" },
    { name: "Low Sperm Count", severity: "chronic" },
    { name: "Poor Sperm Motility", severity: "chronic" },
    { name: "Azoospermia", severity: "chronic" },
    { name: "Oligospermia", severity: "chronic" },
    { name: "Erectile Dysfunction", severity: "chronic" },
    { name: "Varicocele", severity: "chronic" },
    { name: "Hormonal Imbalance", severity: "chronic" },
    { name: "Ovulation Disorder", severity: "chronic" },
    { name: "Blocked Fallopian Tubes", severity: "chronic" },
    { name: "PCOS Related Infertility", severity: "chronic" },
    { name: "Endometriosis Related Infertility", severity: "chronic" },
    { name: "Unexplained Infertility", severity: "chronic" },
    { name: "Secondary Infertility", severity: "chronic" },
    { name: "Premature Ovarian Failure", severity: "chronic" },
    { name: "Hyperprolactinemia", severity: "chronic" },
    { name: "Thyroid Related Infertility", severity: "chronic" },
    { name: "Luteal Phase Defect", severity: "chronic" },
    { name: "Implantation Failure", severity: "chronic" },
    { name: "Recurrent Miscarriage", severity: "chronic" },
    { name: "Genetic Infertility", severity: "chronic" },
    { name: "Uterine Abnormalities", severity: "chronic" },
    { name: "Sperm DNA Fragmentation", severity: "chronic" },
    { name: "Egg Quality Issues", severity: "chronic" },
    { name: "IVF Failure", severity: "chronic" },
    { name: "ICSI Failure", severity: "chronic" },
    { name: "Age Related Infertility", severity: "chronic" },
    { name: "Lifestyle Related Infertility", severity: "chronic" },
    { name: "Smoking Related Infertility", severity: "chronic" },
    { name: "Obesity Related Infertility", severity: "chronic" },
    { name: "Stress Related Infertility", severity: "chronic" },
    { name: "Infection Related Infertility", severity: "chronic" },
    { name: "Ejaculatory Disorder", severity: "chronic" },
    { name: "Sexual Dysfunction", severity: "chronic" },
    { name: "Hormone Therapy Failure", severity: "chronic" },
    { name: "Ovarian Reserve Decrease", severity: "chronic" },
    { name: "Tubal Damage", severity: "chronic" },
    { name: "Endocrine Disorder", severity: "chronic" }
],
"Plastic Surgery": [
    { name: "Burn Reconstruction", severity: "chronic" },
    { name: "Scar Revision", severity: "mild" },
    { name: "Keloid", severity: "chronic" },
    { name: "Hypertrophic Scar", severity: "chronic" },
    { name: "Cleft Lip", severity: "chronic" },
    { name: "Cleft Palate", severity: "chronic" },
    { name: "Post Burn Contracture", severity: "chronic" },
    { name: "Facial Trauma", severity: "acute" },
    { name: "Skin Graft", severity: "acute" },
    { name: "Flap Surgery Complication", severity: "acute" },
    { name: "Hand Reconstruction", severity: "chronic" },
    { name: "Pressure Ulcer", severity: "chronic" },
    { name: "Chronic Wound", severity: "chronic" },
    { name: "Dog Bite Injury", severity: "acute" },
    { name: "Facial Laceration", severity: "acute" },
    { name: "Nasal Deformity", severity: "chronic" },
    { name: "Ear Deformity", severity: "chronic" },
    { name: "Facial Asymmetry", severity: "chronic" },
    { name: "Gynecomastia", severity: "chronic" },
    { name: "Breast Reconstruction", severity: "chronic" },
    { name: "Post Cancer Reconstruction", severity: "chronic" },
    { name: "Aesthetic Complication", severity: "acute" },
    { name: "Implant Infection", severity: "acute" },
    { name: "Skin Necrosis", severity: "acute" },
    { name: "Body Contouring", severity: "mild" },
    { name: "Facial Aging", severity: "mild" },
    { name: "Wrinkle Correction", severity: "mild" },
    { name: "Fat Necrosis", severity: "chronic" },
    { name: "Post Surgical Scar", severity: "chronic" },
    { name: "Burn Injury Face", severity: "acute" },
    { name: "Reconstructive Failure", severity: "acute" }
],
"Newborn Care": [
    { name: "Neonatal Jaundice", severity: "acute" },
    { name: "Prematurity", severity: "chronic" },
    { name: "Low Birth Weight", severity: "chronic" },
    { name: "Birth Asphyxia", severity: "acute" },
    { name: "Neonatal Sepsis", severity: "acute" },
    { name: "Respiratory Distress Syndrome", severity: "acute" },
    { name: "Neonatal Hypoglycemia", severity: "acute" },
    { name: "Neonatal Infection", severity: "acute" },
    { name: "Congenital Anomalies", severity: "chronic" },
    { name: "Neonatal Anemia", severity: "chronic" },
    { name: "Neonatal Seizures", severity: "acute" },
    { name: "Neonatal Pneumonia", severity: "acute" },
    { name: "Meconium Aspiration", severity: "acute" },
    { name: "Neonatal Hypothermia", severity: "acute" },
    { name: "Neonatal Shock", severity: "acute" },
    { name: "Feeding Difficulty", severity: "acute" },
    { name: "Neonatal Vomiting", severity: "acute" },
    { name: "Neonatal Diarrhea", severity: "acute" },
    { name: "Congenital Heart Disease", severity: "chronic" },
    { name: "Neonatal Apnea", severity: "acute" },
    { name: "Neonatal Cyanosis", severity: "acute" },
    { name: "Neonatal Bleeding", severity: "acute" },
    { name: "Umbilical Infection", severity: "acute" },
    { name: "Neonatal Skin Rash", severity: "acute" },
    { name: "Neonatal Eye Infection", severity: "acute" },
    { name: "Neonatal Hearing Loss", severity: "chronic" },
    { name: "Birth Trauma", severity: "acute" },
    { name: "Neonatal Metabolic Disorder", severity: "chronic" },
    { name: "Neonatal Growth Restriction", severity: "chronic" },
    { name: "Neonatal Hypoxia", severity: "acute" }
]


};


// Wrapper for diseases data - using existing diseasesBySpecialty
// Maps severity levels for color coding:
// - acute/severe → red (#dc2626)
// - chronic/moderate → yellow (#ca8a04)  
// - mild → green (#15803d)

function getDiseasesBySpecialty(specialty) {
    if (diseasesBySpecialty && diseasesBySpecialty[specialty]) {
        return diseasesBySpecialty[specialty];
    }
    return [];
}

function searchDiseases(searchTerm, specialty) {
    const diseases = getDiseasesBySpecialty(specialty);
    const term = searchTerm.toLowerCase();
    
    return diseases
        .filter(d => d.name.toLowerCase().includes(term))
        .map(d => ({
            id: d.name.replace(/\s+/g, '_').toLowerCase(),
            name: d.name,
            severity: mappingSeverityToUILevel(d.severity)
        }));
}

// Map disease severity to UI severity levels (severe/moderate/mild)
function mappingSeverityToUILevel(dbSeverity) {
    const severityMap = {
        'acute': 'severe',      // acute → red
        'severe': 'severe',     // severe → red
        'chronic': 'moderate',  // chronic → yellow
        'moderate': 'moderate', // moderate → yellow
        'mild': 'mild'          // mild → green
    };
    return severityMap[dbSeverity] || 'moderate';
}

